language: python
install:
  - sudo apt-get update
  - sudo apt-get -y install libav-tools
  - pip install tox
  - cd coconuts/static
  - npm install
  - npm install grunt-cli
  - cd ../..
script:
  - tox
  - cd coconuts/static
  - node_modules/grunt-cli/bin/grunt karma
