language: python
python:
  - "2.7"
env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
install:
  - pip install Django==$DJANGO pillow
  - cd coconuts/static
  - npm install
  - npm install grunt-cli
  - cd ../..
script:
  - python manage.py test coconuts
  - cd coconuts/static
  - node_modules/grunt-cli/bin/grunt karma
