language: python
python:
  - "2.7"
env:
  - DJANGO=1.4.6
  - DJANGO=1.5.2
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q PIL --use-mirrors
script: python manage.py test coconuts
