sudo: false
language: python
python:
  - "2.7"
env:
  - DJANGO="Django>=1.4,<1.5"
  - DJANGO="Django>=1.5,<1.6"
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"
install:
  - pip install $DJANGO pillow
  - cd coconuts/static
  - npm install
  - npm install grunt-cli
  - cd ../..
script:
  - python manage.py test coconuts
  - cd coconuts/static
  - node_modules/grunt-cli/bin/grunt karma
